version: "3.9"
services:
  postgres:
    image: postgres:latest
    command:
      - "postgres"
      - "-c"
      - "max_connections=50"
      - "-c"
      - "shared_buffers=1GB"
      - "-c"
      - "effective_cache_size=4GB"
      - "-c"
      - "work_mem=16MB"
      - "-c"
      - "maintenance_work_mem=512MB"
      - "-c"
      - "random_page_cost=1.1"
      - "-c"
      - "temp_file_limit=10GB"
      - "-c"
      - "log_min_duration_statement=200ms"
      - "-c"
      - "idle_in_transaction_session_timeout=10s"
      - "-c"
      - "lock_timeout=1s"
      - "-c"
      - "statement_timeout=60s"
      - "-c"
      - "shared_preload_libraries=pg_stat_statements"
      - "-c"
      - "pg_stat_statements.max=10000"
      - "-c"
      - "pg_stat_statements.track=all"
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    volumes:
      - postgres:/var/lib/postgres/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 4G

  quote_book:
    build:
      context: .
    depends_on:
      - postgres
    environment:
      DATABASE_URL: "${DATABASE_URL:-postgresql://postgres:postgres@postgres/quote_book_prod}"
      PHX_SERVER: "${PHX_SERVER:-TRUE}"
      PHX_HOST: "${PHX_HOST}"
      SECRET_KEY_BASE: "${SECRET_KEY_BASE}"
      VK_TOKEN: "${VK_TOKEN}"
      GROUP_ID: "${GROUP_ID}"
    ports:
      - ${PORT}:4000
    volumes:
      - attachments:/app/priv/static/attachments

volumes:
  postgres:
  attachments: