services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: quote_book_prod
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    restart: unless-stopped

  site-screenshoter:
    build:
      context: site-screenshoter
    restart: unless-stopped
    environment:
      PORT: 80

  quote-book:
    build:
      context: .
    depends_on:
      - postgres
      - site-screenshoter
    environment:
      DATABASE_URL: "${DATABASE_URL:-postgresql://postgres:postgres@postgres/quote_book_prod}"
      PHX_SERVER: "${PHX_SERVER:-TRUE}"
      PHX_HOST: "${PHX_HOST}"
      SECRET_KEY_BASE: "${SECRET_KEY_BASE}"
      VK_TOKEN: "${VK_TOKEN}"
    ports:
      - ${PORT}:4000
    volumes:
      - attachments:/app/attachments

volumes:
  postgres:
  attachments:
